name: MCONE-SkyPvP
version: 3.0.1
author: Dominik Lippl
main: eu.mcone.skypvp.SkyPvP
depend: [MCONE-BukkitCoreSystem,MCONE-GameSystem]

commands:
  kit:
    aliases: kit
    description: Changes own KitManager
  enderchest:
    aliases: ec
    description: Opens players enderchest
  workbench:
    aliases: wb
    description: Opens players workbench
  spawn:
    description: Teleports to spawn
  shop:
    description: Opens Shop inventory
    aliases: s
  random:
    description: Pick random winner
    permission: skypvp.random

permissions:
  skypvp:
    description: Main Permission
    children:
      skypvp.spawn:
        description: Teleport to Spawn
        children:
          skypvp.spawn.set:
            description: Allows to set several spawns
      skypvp.random:
        description: Allows to pick a random winner
      skypvp.kit:
        description: Allows to get all KitManager
        children:
          skypvp.kit.iron:
            description: Iron Kit
          skypvp.kit.diamond:
            description: Diamond Kit
          skypvp.kit.emerald:
            description: Emerald Kit