name: MCONE-SkyPvP
version: 2.3
author: TwinsterHD
main: de.Dominik.SkyPvP.Main
depend: [MCONE-BukkitCoreSystem]
commands:
     kit:
     kits:
     head:
     setspawnshop:
     setspawnvote:
     setspawnkits:
     set:
     ec:
     wb:
     spawn:
     shop:
     random: